# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    branches: [ "main" ]

env:
  SCHEME: ForgeUIPackage
  TEST_DEVICE: platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2

jobs:
  build:

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: Get Swift version
        run: swift --version
      - name: Show eligible build destinations for ForgeUIPackage
        run: xcodebuild -showdestinations -scheme '${{ env.SCHEME }}'
      - name: Build
        run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' build
      - name: Run tests
        run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' test
