# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8.0"
      - name: Get Swift version
        run: swift --version
      - name: Show eligible build destinations for ForgeUIPackage
        run: xcodebuild -showdestinations -scheme ForgeUIPackage
      - name: Build and Tests
        run: xcodebuild test -scheme ForgeUIPackage -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 14 Pro'
#      - name: Run tests
#        run: swift test

